<script src="<?= base_url() ?>public/jquery/select2/select2.min.js" type="text/javascript"></script>
<script src="<?= base_url() ?>public/jquery/jquery.class.min.js" type="text/javascript"></script>
<script src="<?= base_url() ?>public/jquery/defunkt-jquery-pjax/jquery.pjax.js" type="text/javascript"></script>
<script src="<?= base_url() ?>public/jquery/jstorage.min.js" type="text/javascript"></script>
<script src="<?= base_url() ?>public/jquery/autosize/jquery.autosize-min.js" type="text/javascript"></script>
<script src="<?= base_url() ?>public/jquery/rochal-jQuery-slimScroll/slimScroll.min.js" type="text/javascript"></script>
<script src="<?= base_url() ?>public/jquery/pnotify/jquery.pnotify.min.js" type="text/javascript"></script>
<script src="<?= base_url() ?>public/jquery/jquery.hoverIntent.minified.js" type="text/javascript"></script>
<script src="<?= base_url() ?>public/jquery/jquery.additions.js" type="text/javascript"></script>
<script src="<?= base_url() ?>public/jquery/helper.js" type="text/javascript"></script>
<script src="<?= base_url() ?>public/jquery/Connector.js" type="text/javascript"></script>
<script src="<?= base_url() ?>public/jquery/posabsolute-jQuery-Validation-Engine/js/jquery.validationEngine.js" type="text/javascript"></script>
<script src="<?= base_url() ?>public/jquery/posabsolute-jQuery-Validation-Engine/js/jquery.validationEngine-en.js" type="text/javascript"></script>
<script src="<?= base_url() ?>public/guidersjs/guiders-1.2.6.js" type="text/javascript"></script>
<script src="<?= base_url() ?>public/jquery/datepicker/js/datepicker.js" type="text/javascript"></script>
<script src="<?= base_url() ?>public/jquery/dangrossman-bootstrap-daterangepicker/date.js" type="text/javascript"></script>
<script src="<?= base_url() ?>public/jquery/jquery.ba-outside-events.min.js" type="text/javascript"></script>
